version: '3.1'
services:
  stat-server:
    build: stat/stat-server
    container_name: stat-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/stat-db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING-DATASOURCE_PASSWORD=password

  stat-db:
    image: postgres:15-alpine
    container_name: stat-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stat-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: ewm-service
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stat-server
    environment:
      - STAT_URL=http://stat-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING-DATASOURCE_PASSWORD=password

  ewm-db:
    image: postgres:15-alpine
    container_name: emw-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password